config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end #This is a nested profile behind a user
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
        validates :name, presence: true
        validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base #Each profile must have a seperate record
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token #stripe_card_token hidden field value
  
  def save_with_payment #method used in /app/controllers/users/registrations_controller.rb
    if valid? #If user filled out form properly
      customer = Stripe::Customer.create(description: email, plan: plan_id, source: stripe_card_token)
      self.stripe_customer_token = customer.id #setting property of user to user id returned from stripe
      save! #saving entire user object to database by creating new migration file
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  
  protected #We are whitelisting this parameter to securley allow people to submit things to us from the internet
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
  end 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            
            ContactMailer.contact_email(name, email, body).deliver
            
            flash[:success] = 'Message sent.'
            redirect_to new_contact_path
        else
            flash[:info] = 'Error occured, message has not been sent.'
            redirect_to new_contact_path
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
end

app/controllers/users/profiles_controller.rb
class ProfilesController < ApplicationController
    def new
       # form where a user can fill out their own profile.
       @user = User.find( params[:user_id] )
#lets reach into database and find the user that is logged in
#params accessess the hash that is generated in the http response(URL). 
#The hash info in this case is in the user link in home.html.erb
#to demonstrate check the line below
#      @variable = params[:user_id]
#now goto 
       @profile = @user.build_profile #this works because we have the nested profile inside routes.rb
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController  #given to us by Devise
    #creating a class Users and inheriting devise
    before_filter :select_plan, only: :new
    #define select_plan function below in a private file gx 
    
    
    def create  #When the user submits their form
       super do |resource| #importing to create action code that is inside the devise gem
          if params[:plan] #when user submits basic or pro form
              resource.plan_id = params[:plan] #were going to catch that form and see if param :plan was submitted and if yes then we save to resource.plan_id
              if resource.plan_id == 2 # if User.first_plan.id = 2
                  resource.save_with_payment # if id does = 2 then we save_with_payment defined in models/user.rb otherwise
              else  #if id = 1
                  resource.save #just do a regular save to resources
              end
          end
       end
    end
    
    private
        def select_plan
            unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2' )
            #unless the user comes from a button with value 1 or 2
            flash[:notice] = "Please select a membership plan to sign up."
            #if the value is not 1 or 2 flash this notice to the user
            redirect_to root_url
            #and redirect them to the root url
            end
        end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well">
            <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.email_field :email, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :comments %>
                    <%= f.text_area :comments, class: 'form-control' %>
                </div>
                <%= f.submit 'Submit', class: 'btn btn-default' %>
        </div>
    </div>
    
    <% end %>
    
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevMatch</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application'%>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class='container'>
      <div class='navbar-header'>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fa fa-users"></i>
          DevMatch
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="navbar-nav navbar-right">
          <% if current_user %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "New Contact", new_contact_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  
<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  
  <%= yield %>
  <% end %>
</div>

</body>

</html>

app/views/pages/about.html.erb
<h2>About</h2>

app/views/pages/home.html.erb
<%= link_to "Create your profile!.", new_user_profile_path(current_user) if current_user%>
<!--current_user is available from devise gem and sets user_id: dynamiclylinkedcurrentuserthatsloggedin-->
<!--new_user_profile is available from the routes.rb when you bundle exec rake routes-->
<!--if current_user means if the user is logged in-->

<div class="jumbotron text-center">
    <h1>Welcome to Devmatch</h1>
    <h3>This is a site im making from a tutorial for developers to socialize</h3>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h2 class="text-center">Basic Membership</h2>
            <h4>Sign up for free and get basic access to the community.</h4>
            <br/>
            <%= link_to "Sign up for FREE", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
        </div>
    </div>
    <div class="col-md-6">
        <div class="well">
            <h2 class="text-center">Pro Membership</h2>
            <h4>Sign up for a Pro account for $10/month to gain access to all our members!</h4>
            <%= link_to "Sign up for PRO", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
Form for user to create profile. First name, last name etc.....
<!--This is to demonstrate the profiles_controller.rb hash dynamic connection -->
<!--     (ruby)@variable(ruby)   -->
<!-- the @variable above links to the @ variable inside the profiles_controller and spits out the -->
<!-- user_id param. Alternatively if we include something like whatyever_path(current_user, anotherhash: hi)-->
<!-- in the home.html.erb and then link that variable inside the profiles_controller with -->
<!-- @variable = (params[:anotherhash]) then we will get an output of hi -->